apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website-ing
  namespace: website
spec:
  ingressClassName: nginx
  rules:
    - host: app.berrouyne.space
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: website-svc
                port:
                  number: 80
